Adds cleanupsyncs command parameters
learningequality/morango pull request #186
Opened 2023-07-13 16:09 UTC by akolson

## Summary

This PR adds parameters for sync filter and instance (server or client) to `cleanupsyncs` parameters added include;
- `sync_filter `
- `client_instance_id `
- `server_instance_id `
- `push` and `pull`

## TODO

- [x] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed
Fixes #184 

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

2023-07-17 21:31 UTC, bjester requested changes
Looks great! Although, I believe I misled you about the dashes and underscores (messaged on Slack too). 

Please define the arguments with `-` (dashes) instead of `_` (underscores).

2023-07-18 05:35 UTC, akolson commented
Changes have been implemented as requested by reviewer.

2023-07-18 14:05 UTC, bjester approved these changes
Approved! Tests pass locally and we'll make a 0.6.x release then merge up to 0.7.x

2023-07-18 14:05 UTC, merged

2023-07-18 14:08 UTC, bjester commented on CHANGELOG.md
> +## 0.16.17
Oh oops! I just noticed this is `0.16...` not `0.6` :smile:

2023-07-18 14:24 UTC, akolson commented on CHANGELOG.md
> +## 0.16.17
Let me make change

2023-07-18 14:25 UTC, akolson commented on CHANGELOG.md
> +## 0.16.17
0.16 effect 😄